style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/sergelogvinov/proxmox-csi-plugin
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      chore: Miscellaneous
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
