apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: kube-system
spec:
  hostname: ubuntu
  subdomain: default
  hostPID: true
  hostNetwork: true
  containers:
  - image: ubuntu
    command:
      - sleep
      - "14d"
    name: ubuntu
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_RAWIO
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: sys
      mountPath: /sys
    - name: root
      mountPath: /mnt/root
      readOnly: true
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - name: tmp
      mountPath: /tmp
  tolerations:
    - operator: Exists
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: sys
      hostPath:
        path: /sys
    - name: root
      hostPath:
        path: /
    - hostPath:
        path: /lib/modules
      name: lib-modules
    - name: tmp
      emptyDir:
        medium: Memory
  nodeSelector:
    kubernetes.io/hostname: kube-11
