allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-rbd
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: rbd
  # storageFormat: qcow2
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
#   - matchLabelExpressions:
#       - key: topology.kubernetes.io/region
#         values:
#           - region-1
