# dd if=/dev/urandom bs=1 count=16 2>/dev/null | hexdump -e '"%00x"' > csi-secret.secret
# kubectl -n kube-system create secret generic proxmox-csi-secret --from-file=encryption-passphrase=csi-secret.secret --dry-run=client -oyaml
---
apiVersion: v1
data:
  encryption-passphrase: MWYwMzkyODAzM2RkYTJlNGZkMzQ3ZTQ0MjY2Y2ZiYw==
kind: Secret
metadata:
  creationTimestamp: null
  name: proxmox-csi-secret
  namespace: kube-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-secret
parameters:
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/node-stage-secret-name: "proxmox-csi-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
  csi.storage.k8s.io/node-expand-secret-name: "proxmox-csi-secret"
  csi.storage.k8s.io/node-expand-secret-namespace: "kube-system"
  storage: lvm
mountOptions:
  - discard
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
