name: Build check

on:
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "pkg/**"
      - "Dockerfile"

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up go
        timeout-minutes: 5
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout=5m --config=.golangci.yml
      - name: Unit
        run: make unit
      - name: Build
        timeout-minutes: 10
        run: make images
        env:
          PLATFORM: linux/amd64
      - name: Check node tools
        timeout-minutes: 5
        run: make image-tools-check
        env:
          PLATFORM: linux/amd64
