name: Conformance check

on:
  pull_request:
    branches:
      - main
      - sm-moshi/main

jobs:
  conform:
    name: Conformance
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout base branch
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: git fetch --no-tags origin "${BASE_REF}:${BASE_REF}"

      - name: Conform action
        uses: talos-systems/conform@cfdb3cce90daece912e6a5cb3f20b2316a78a5bf # v0.1.0-alpha.31
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
