name: Release check

on:
  pull_request:
    branches:
      - main

jobs:
  build-publish:
    name: "Check release docs"
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if: startsWith(github.head_ref, 'release-')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Release version
        if: startsWith(github.head_ref, 'release-please')
        run: jq -r '"TAG=v"+.[]' hack/release-please-manifest.json >> "$GITHUB_ENV"

      - name: Helm docs
        uses: gabe565/setup-helm-docs-action@d5c35bdc9133cfbea3b671acadf50a29029e87c2 # v1.0.4
        with:
          version: v1.11.3

      - name: Generate
        run: make docs
      - name: Check
        run: git diff --exit-code

  build-publish-cli:
    name: "Check cli tool"
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if: startsWith(github.head_ref, 'release-')
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          version: "v2.12.7"
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
