name: Release please

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create release PR
        id: release
<<<<<<< HEAD
        uses: googleapis/release-please-action@v5
=======
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
>>>>>>> origin/renovate/github-actions
        with:
          config-file: hack/release-please-config.json
          manifest-file: hack/release-please-manifest.json
