name: Release check

on:
  pull_request:
    branches:
      - main

jobs:
  build-publish:
    name: "Check release docs"
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if:  startsWith(github.head_ref, 'release-')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Release version
        if:  startsWith(github.head_ref, 'release-please')
        run: jq -r '"TAG=v"+.[]' hack/release-please-manifest.json >> "$GITHUB_ENV"

      - name: Helm docs
        uses: gabe565/setup-helm-docs-action@v1
        with:
          version: v1.11.3

      - name: Generate
        run: make docs
      - name: Check
        run: git diff --exit-code

  build-publish-cli:
    name: "Check cli tool"
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if:  startsWith(github.head_ref, 'release-')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
